'use strict';
const $ = id => document.getElementById(id);
let language = 'ar';
const translations = {
'واتساب':'WhatsApp','لوحة WAHA ↗':'WAHA dashboard ↗','رسالة واحدة كل دقيقة':'One message per minute','الإرسال الجماعي':'Bulk messaging','أضف الأرقام والرسالة، راجع الحملة، ثم ابدأ الإرسال عندما تكون جاهزًا.':'Add recipients and a message, review the campaign, then start when ready.',
'حملة جديدة':'New campaign','اسم الحملة':'Campaign name','أرقام المستلمين':'Recipient numbers','نص الرسالة':'Message text','رقم واحد في كل سطر. الرقم الكويتي 8 أرقام أو رقم دولي يبدأ بكود الدولة. الأرقام المكررة تُحذف تلقائيًا.':'One number per line. Eight digits means Kuwait; international numbers include the country code. Duplicates are removed.',
'أو اختر ملف CSV / TXT بعمود أرقام واحد':'Or select a one-column CSV / TXT file','نص واحد لكل المستلمين؛ لا توجد متغيرات أو مرفقات في هذه النسخة.':'The same plain text goes to every recipient. Variables and attachments are not supported.',
'حفظ ومراجعة الحملة':'Save and review campaign','الحفظ لا يرسل أي رسالة. الحد التقني للحملة 10000 رقم.':'Saving sends nothing. Technical limit: 10,000 numbers per campaign.',
'الحملات':'Campaigns','تحديث':'Refresh','لم تُضف حملات بعد. الإرسال متوقف.':'No campaigns yet. Sending is stopped.',
'الفاصل 60 ثانية على الأقل بعد كل محاولة. يتم تشغيل حملة واحدة في المرة. توقف الخادم يوقف الحملات، والاستكمال يحتاج قرارًا منك. الإرسال مخصص لمستلمين موافقين؛ الفاصل لا يضمن عدم تقييد رقم واتساب.':'At least 60 seconds between attempts. One campaign runs at a time. Server restarts pause campaigns; you must resume manually. Send to consenting recipients; the interval does not guarantee protection from WhatsApp restrictions.',
'المجموع':'Total','قبلها WAHA':'Accepted by WAHA','بانتظار الإرسال':'Pending','فشلت':'Failed','غير مؤكدة':'Uncertain','متخطاة':'Skipped','بدء الإرسال':'Start sending','استكمال بقية الأرقام':'Resume pending numbers','إيقاف الإرسال':'Pause sending','تحققت: الرسالة أُرسلت':'Verified: message was sent','تخطي المحاولة بدون إعادة إرسال':'Skip without resending','مراجعة الأرقام والحالات':'Review numbers and statuses','الرقم':'Number','الحالة':'Status',
'«قبلها WAHA» يعني نجاح طلب الإرسال؛ لا يؤكد وصولها أو قراءتها. الرسائل الفاشلة لا تُعاد تلقائيًا.':'Accepted by WAHA means the send request succeeded; delivery and read status are not confirmed. Failed messages are not retried automatically.',
'بدأت الحملة. تقدر توقفها في أي وقت.':'Campaign started. You can pause it at any time.','تم إيقاف الحملة. أي رسالة أُرسلت بالفعل لا يمكن سحبها.':'Campaign paused. Messages already sent cannot be recalled.','تم تسجيل قرار المراجعة. اضغط استكمال لإرسال بقية الأرقام.':'Review decision recorded. Resume to send remaining pending messages.',
'تم حفظ المسودة وإزالة تكرار الأرقام. لم يتم إرسال أي رسالة. راجعها أسفل الصفحة قبل البدء.':'Draft saved and duplicate numbers removed. Nothing was sent. Review below before starting.',
'الملف أكبر من الحد المسموح 700 كيلوبايت.':'The file exceeds the 700 KB limit.','تعذر الاتصال بالسيرفر.':'Could not connect to the server.',
'تأكدت من إرسال الرسالة للمستلم ذي الحالة غير المؤكدة؟':'Have you verified this uncertain message was sent?',
'سيتم تخطي المحاولة غير المؤكدة، ولن نعيد إرسالها. متابعة؟':'The uncertain attempt will be skipped without resending. Continue?',
'الخادم أعيد تشغيله؛ اضغط استكمال عندما تكون جاهزًا.':'Server restarted; resume when ready.','جلسة واتساب غير متصلة. تحقق من WAHA ثم استكمل.':'WhatsApp is offline. Check WAHA before resuming.','الإرسال انقطع أثناء المحاولة. تحقق من واتساب قبل تحديد النتيجة.':'The send was interrupted. Check WhatsApp before resolving it.','لم يصل تأكيد واضح من WAHA. تحقق من واتساب قبل تحديد النتيجة.':'No clear WAHA confirmation. Check WhatsApp before resolving it.','لم يصل رقم تعريف للرسالة. تحقق من واتساب قبل تحديد النتيجة.':'No message ID returned. Check WhatsApp before resolving it.','توقف التنفيذ بسبب خطأ؛ راجع المحاولة قبل الاستكمال.':'Worker stopped after an error. Review the attempt before resuming.'};
const statesEnglish={draft:'Draft — not started',running:'Sending',paused:'Paused',uncertain:'Uncertain — review required',complete:'Attempts complete',pending:'Pending',sending:'Sending',sent:'Accepted by WAHA',failed:'Failed',skipped:'Skipped'};
const tr = text => language==='en' ? (translations[text] || text) : text;
const stateText = state => language==='en' ? (statesEnglish[state]||state) : (states[state]||state);

const states = {draft:'مسودة — لم يبدأ الإرسال',running:'قيد الإرسال',paused:'متوقفة',uncertain:'نتيجة غير مؤكدة — راجع قبل الاستكمال',complete:'اكتملت المحاولات',pending:'بانتظار الإرسال',sending:'جارٍ الإرسال',sent:'قبلها WAHA',failed:'فشلت',skipped:'تم تخطيها'};
const errors = {server_restart:'الخادم أعيد تشغيله؛ اضغط استكمال عندما تكون جاهزًا.',session_unavailable:'جلسة واتساب غير متصلة. تحقق من WAHA ثم استكمل.',interrupted_send:'الإرسال انقطع أثناء المحاولة. تحقق من واتساب قبل تحديد النتيجة.',ambiguous_response:'لم يصل تأكيد واضح من WAHA. تحقق من واتساب قبل تحديد النتيجة.',missing_message_id:'لم يصل رقم تعريف للرسالة. تحقق من واتساب قبل تحديد النتيجة.',worker_failure:'توقف التنفيذ بسبب خطأ؛ راجع المحاولة قبل الاستكمال.'};
let busy = false;
function notice(text, error=false){$('notice').textContent=tr(text);$('notice').classList.toggle('error',error);}
async function api(path, body){const response=await fetch('/bulk/api/'+path,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json','Accept-Language':language}:{'Accept-Language':language},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر الاتصال بالسيرفر.');return data;}
function el(tag,text,className,raw=false){const node=document.createElement(tag);if(text!==undefined)node.textContent=raw?text:tr(text);if(className)node.className=className;return node;}
async function action(id,name,body={}){if(busy)return;busy=true;try{await api('campaigns/'+id+'/'+name,body);notice(name==='start'?'بدأت الحملة. تقدر توقفها في أي وقت.':name==='pause'?'تم إيقاف الحملة. أي رسالة أُرسلت بالفعل لا يمكن سحبها.':'تم تسجيل قرار المراجعة. اضغط استكمال لإرسال بقية الأرقام.');await refresh();}catch(error){notice(error.message,true);}finally{busy=false;}}
function button(text,fn,className){const b=el('button',text,className);b.type='button';b.addEventListener('click',fn);return b;}
function render(data){const root=$('campaigns');const opened=new Set([...root.querySelectorAll('details[open]')].map(n=>n.dataset.id));root.replaceChildren();$('empty').hidden=!!data.campaigns.length;for(const c of data.campaigns){const card=el('article',undefined,'campaign');const title=el('div',undefined,'campaign-title');title.append(el('h3',c.name,undefined,true),el('span',stateText(c.state),'badge'));card.append(title);const stats=el('div',undefined,'stats');for(const [label,value] of [['المجموع',c.total],['قبلها WAHA',c.counts.sent||0],['بانتظار الإرسال',c.counts.pending||0],['فشلت',c.counts.failed||0],['غير مؤكدة',c.counts.uncertain||0],['متخطاة',c.counts.skipped||0]])stats.append(el('span',tr(label)+': '+value));card.append(stats,el('div',c.message,'message-preview',true));if(c.error)card.append(el('p',errors[c.error]||(language==='en'?'Sending paused: ':'توقف الإرسال: ')+c.error,'error-text'));const actions=el('div',undefined,'actions');if(['draft','paused'].includes(c.state)&&(c.counts.pending||0)>0)actions.append(button(c.state==='draft'?'بدء الإرسال':'استكمال بقية الأرقام',()=>{if(confirm(language==='en'?'I reviewed the message and numbers, and recipients consent. Sending starts now, with at least a minute between attempts.\nStart '+c.name+'?':'راجعت نص الرسالة والأرقام، والمستلمون موافقون على استقبالها.\nسيبدأ الإرسال الآن بفاصل دقيقة على الأقل.\nهل تريد بدء الحملة «'+c.name+'»؟'))action(c.id,'start',{confirmed:true});},'primary'));if(c.state==='running')actions.append(button('إيقاف الإرسال',()=>action(c.id,'pause')));if(c.state==='uncertain'){actions.append(button('تحققت: الرسالة أُرسلت',()=>{if(confirm(tr('تأكدت من إرسال الرسالة للمستلم ذي الحالة غير المؤكدة؟')))action(c.id,'resolve',{decision:'sent'});}));actions.append(button('تخطي المحاولة بدون إعادة إرسال',()=>{if(confirm(tr('سيتم تخطي المحاولة غير المؤكدة، ولن نعيد إرسالها. متابعة؟')))action(c.id,'resolve',{decision:'skipped'});}));}card.append(actions);const details=el('details');details.dataset.id=String(c.id);details.open=opened.has(String(c.id));details.append(el('summary',tr('مراجعة الأرقام والحالات')+(c.total>100?(language==='en'?' — first 100 of ':' — أول 100 رقم من ')+c.total:'')));const wrapper=el('div',undefined,'table-wrap');const table=el('table');const header=el('tr');header.append(el('th','الرقم'),el('th','الحالة'));table.append(header);for(const r of c.recipients){const row=el('tr');row.append(el('td','+'+r.phone,'phone'),el('td',stateText(r.state)));table.append(row);}wrapper.append(table);details.append(wrapper);card.append(details);card.append(el('p','«قبلها WAHA» يعني نجاح طلب الإرسال؛ لا يؤكد وصولها أو قراءتها. الرسائل الفاشلة لا تُعاد تلقائيًا.','hint'));root.append(card);}}
async function refresh(){try{render(await api('campaigns'));}catch(error){notice(error.message,true);}}
$('draft').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;busy=true;const submit=event.target.querySelector('button');submit.disabled=true;try{await api('campaigns',{name:$('name').value,numbers:$('numbers').value,message:$('message').value});notice('تم حفظ المسودة وإزالة تكرار الأرقام. لم يتم إرسال أي رسالة. راجعها أسفل الصفحة قبل البدء.');event.target.reset();await refresh();}catch(error){notice(error.message,true);}finally{busy=false;submit.disabled=false;}});
$('file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;if(file.size>700000){notice('الملف أكبر من الحد المسموح 700 كيلوبايت.',true);return;}$('numbers').value=await file.text();});
$('refresh').addEventListener('click',refresh);refresh();setInterval(()=>{if(!busy)refresh();},5000);

$('language').addEventListener('click',()=>{
const english=language==='ar';language=english?'en':'ar';document.documentElement.lang=language;document.documentElement.dir=english?'ltr':'rtl';document.title=english?'Nutreeze | Bulk messaging':'Nutreeze | الإرسال الجماعي';
const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const reverse=Object.fromEntries(Object.entries(translations).map(([a,e])=>[e,a]));let node;
while((node=walker.nextNode())){if(node.parentElement.closest('#campaigns,#notice,#language'))continue;const key=node.nodeValue.trim();const value=english?translations[key]:reverse[key];if(value)node.nodeValue=node.nodeValue.replace(key,value);}
$('language').textContent=english?'العربية':'English';$('empty').textContent=tr('لم تُضف حملات بعد. الإرسال متوقف.');$('notice').textContent='';refresh();
});
